[package]
name = "sort_algos"
version = "0.1.2"
edition = "2021"
license = "MIT"
description = "Sorting alghoritms"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
